from pandan import Pandan
from pandan import NumericPandan

if __name__ == "__main__":
    p = Pandan("decision01", 10, 0.7)
    print(p.add_evidence("user01"))
    print(p.add_evidence("user02"))
    print(p.add_evidence("user01"))
    print(p.add_evidence("user03"))
    print(p.add_evidence("user01"))
    print(p.add_evidence("user02"))
    print(p.add_evidence("user01"))
    print(p.add_evidence("user03"))
    print(p.add_evidence("user01"))
    print(p.add_evidence("user02"))
    print(p.add_evidence("user01"))
    print(p.add_evidence("user03"))
    print(p.add_evidence("user01"))
    print(p.add_evidence("user01"))
    print(p.add_evidence("user01"))
    print(p.add_evidence("user01"))
    print(p.add_evidence("user01"))
    print(p.add_evidence("user01"))
    print(p.add_evidence("user01"))
    print(p.add_evidence("user01"))
    print(p.add_evidence("user01"))
    print(p.add_evidence("user01"))
    print(p.add_evidence("user01"))
    print(p.add_evidence("user01"))
    print(p.add_evidence("user01"))
    print(p.add_evidence("user01"))
    print(p.add_evidence("user01"))
    print(p.add_evidence("user01"))

    p = NumericPandan("decision02", 5)
    print(p.add_evidence(1))
    print(p.add_evidence(2))
    print(p.add_evidence(3))
    print(p.add_evidence(4))
    print(p.add_evidence(5))
    print(p.add_evidence(10))
